import enum


class DASHBOARD_COMMANDS(str, enum.Enum):
    S_DASHBOARD_TEMPLATE = 1


class MANAGE_SEARCH_COMMANDS(str, enum.Enum):
    S_MANAGE_SEARCH_TEMPLATE = 1
    S_MANAGE_SEARCH = 2

class MANAGE_FEEDER_COMMANDS(str, enum.Enum):
    S_MANAGE_REGISTERATION_TEMPLATE = 1
    S_SUBMIT_INSERT = 4
    S_SUBMIT_DELETE = 5
    S_SUBMIT_VIEW = 6

class MANAGE_FEEDER_VERIFICATION_COMMANDS(str, enum.Enum):
    S_MANAGE_VERIFICATION_TEMPLATE = 1
    S_REGISTER_VERIFICATION = 2

class MANAGE_USER_COMMANDS(str, enum.Enum):
    S_MANAGE_USER_TEMPLATE = 1
    S_SUBMIT_INSERT = 5
    S_SUBMIT_UPDATE = 6
    S_SUBMIT_DELETE = 7
    S_SUBMIT_VIEW = 8

class LOGIN_COMMANDS(str, enum.Enum):
    S_VERIFY_LOGIN_REQUEST = 1
    S_LOGIN_TEMPLATE = 2

class SESSION_COMMANDS(enum.Enum):
    S_CREATE = 1
    S_EXISTS = 2
    S_FETCH_USER = 3

class MONGODB_COMMANDS(enum.Enum):
    S_INIT = 0
    S_CREATE = 1
    S_READ = 2
    S_UPDATE = 3
    S_DELETE = 4

class MONGODB_REQUEST_COMMANDS(enum.Enum):
    S_VERIFY_CREDENTIAL = 1
    S_INSERT_USER = 2
    S_UPDATE_USER = 3
    S_DELETE_USER = 4
    S_ALL_USER = 5
    S_SAVE_MESSAGE_MODEL = 6
    S_USER_EXITS = 13
