import enum


class TOPIC_CLASSFIER_COMMANDS(enum.Enum):
    S_GENERATE_CLASSIFIER = 1
    S_PREDICT_CLASSIFIER = 2

class TOPIC_CLASSFIER_MODEL(enum.Enum):
    S_PREDICT_CLASSIFIER = 1

class TOPIC_CLASSFIER_TRAINER(enum.Enum):
    S_GENERATE_CLASSIFIER = 1
    S_CLEAN_DATA = 2